#%RAML 1.0
title: Demo
version: v1
protocols: [ HTTP, HTTPS ]
baseUri: http://api.test.yii/v1

mediaType: [ application/json, application/xml ]

securitySchemes:
  Auth: !include ../../../vendor/yii2lab/yii2-rest/src/domain/docs/securitySchemes/base.raml
#securedBy: [ Auth ]

traits:
  paged:   !include ../../../vendor/yii2lab/yii2-rest/src/domain/docs/traits/paged.raml
  search:   !include ../../../vendor/yii2lab/yii2-rest/src/domain/docs/traits/search.raml
  lang:    !include ../../../vendor/yii2lab/yii2-rest/src/domain/docs/traits/lang.raml
  fields:  !include ../../../vendor/yii2lab/yii2-rest/src/domain/docs/traits/fields.raml
  expand:  !include ../../../vendor/yii2lab/yii2-rest/src/domain/docs/traits/expand.raml
  code200: !include ../../../vendor/yii2lab/yii2-rest/src/domain/docs/traits/codes/200.raml
  code201: !include ../../../vendor/yii2lab/yii2-rest/src/domain/docs/traits/codes/201.raml
  code204: !include ../../../vendor/yii2lab/yii2-rest/src/domain/docs/traits/codes/204.raml
  code304: !include ../../../vendor/yii2lab/yii2-rest/src/domain/docs/traits/codes/304.raml
  code400: !include ../../../vendor/yii2lab/yii2-rest/src/domain/docs/traits/codes/400.raml
  code401: !include ../../../vendor/yii2lab/yii2-rest/src/domain/docs/traits/codes/401.raml
  code403: !include ../../../vendor/yii2lab/yii2-rest/src/domain/docs/traits/codes/403.raml
  code404: !include ../../../vendor/yii2lab/yii2-rest/src/domain/docs/traits/codes/404.raml
  code405: !include ../../../vendor/yii2lab/yii2-rest/src/domain/docs/traits/codes/405.raml
  code415: !include ../../../vendor/yii2lab/yii2-rest/src/domain/docs/traits/codes/415.raml
  code422: !include ../../../vendor/yii2lab/yii2-rest/src/domain/docs/traits/codes/422.raml
  code429: !include ../../../vendor/yii2lab/yii2-rest/src/domain/docs/traits/codes/429.raml
  code500: !include ../../../vendor/yii2lab/yii2-rest/src/domain/docs/traits/codes/500.raml

/auth: !include ../../../vendor/yii2module/yii2-account/src/api/v2/docs/auth/api.raml
/registration: !include ../../../vendor/yii2module/yii2-account/src/api/v2/docs/registration/api.raml
/security: !include ../../../vendor/yii2module/yii2-account/src/api/v2/docs/security/api.raml
/user: !include ../../../vendor/yii2module/yii2-account/src/api/v2/docs/user/api.raml
/profile: !include ../../../vendor/yii2module/yii2-profile/src/api/v2/docs/profile/api.raml
/profile-address: !include ../../../vendor/yii2module/yii2-profile/src/api/v2/docs/profile-address/api.raml
/profile-avatar: !include ../../../vendor/yii2module/yii2-profile/src/api/v2/docs/profile-avatar/api.raml
/profile-person: !include ../../../vendor/yii2module/yii2-profile/src/api/v2/docs/profile-person/api.raml
/city: !include ../../../vendor/yii2lab/yii2-geo/src/api/docs/city/api.raml
/country: !include ../../../vendor/yii2lab/yii2-geo/src/api/docs/country/api.raml
/currency: !include ../../../vendor/yii2lab/yii2-geo/src/api/docs/currency/api.raml
/region: !include ../../../vendor/yii2lab/yii2-geo/src/api/docs/region/api.raml