#!/usr/bin/env php
<?php

use yii2lab\app\domain\helpers\generator\Generator;

@include_once('App.php');
App::init('console');

$sourceDir = 'vendor/yii2lab/yii2-app/src/data/appOnRails';
Generator::generateApplication($sourceDir);
